---
- name: BLAF

  tasks:
  
    - name: Create a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        hostname: qer
        username: asdf
        password: asdf
        folder: /DC1/vm/
