- name: BLAF
  hosts: all
  tasks:

    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vshpere_username }}"
        password: "{{ vsphere_password }}"
        #folder: /DC1/vm/
        name: test_vm_0001
        state: poweredoff
        #guest_id: centos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be deployed
        #esxi_hostname: "{{ esxi_hostname }}"
        disk:
        - size_gb: 10
          type: thin
          datastore: datastore1
        hardware:
          memory_mb: 512
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
          ip: 192.168.5.124
          netmask: 255.255.255.0
          device_type: vmxnet3
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 600
      delegate_to: localhost
      register: deploy_vm
