---
- name: BLAF
- hosts: ala
  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: qer
        username: asdf
        password: asdf
        folder: /DC1/vm/
