---
- name: Remove nginx pky 
  hosts: all
  become: true 
 
  tasks:
 
  - name: remove nginx
    yum: 
      name=nginx
      state=absent
      update_cache=true
  
  - name: remove nginx filesystem
    yum: 
      name=nginx-filesystem
      state=absent
      update_cache=true
