---
- name: Query a user in ISV
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get access token
      uri:
        url: "{{ tenant_url }}/v1.0/endpoint/default/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          grant_type: client_credentials
      register: results
    - set_fact:
        access_token: "{{ results.json.access_token }}"
    - debug:
        var: access_token

    - name: Call ISV SCIM API for Querying users
      uri:
        #url: "{{ tenant_url }}/v2.0/Users?filter=username%20eq%20{{ username }}"
        url: "{{ tenant_url }}/v2.0/Users/cardinality"
        method: GET
        headers:
          Accept: application/scim+json
          #Authorization: "Bearer {{ access_token }}"
        #    body:
        #      filter: "userName eq {{ username }}"
      register: results
    - set_fact:
        isv_users: "{{ results.json.Resources }}"
    - debug:
        var: isv_users