---
- name: Call ISV SCIM API for Querying users
  uri:
    url: "{{ tenant_url }}/v2.0/Users?filter=username%20eq%20{{ username }}"
    method: GET
    headers:
      Accept: application/scim+json
      Authorization: "Bearer {{ access_token }}"
        #    body:
        #      filter: "userName eq {{ username }}"
  register: results
- set_fact:
    isv_users: "{{ results.json.Resources }}"